### ISSUE TITLE
Error "Amino:JSON  with UTC" when starting iris testnet error

### ISSUE THREAD

**Issue by shenzhun** [irisnet/testnets#20]
iris: v0.3.1, v0.3.0
Testnet: fuxi-1002
OS: ubuntu 16.04, AWS

`./iris start --home=.iris`

`I[08-02|15:12:42.155] Starting ABCI with Tendermint                module=main
ERROR: Error{Amino:JSON time must be UTC and end with 'Z' but got "2018-07-25T14:00:24.231866967+08:00".}`

**Comment by zhangyelong** [comment]
fuxi-1002 is based on version 0.2.x
