### ISSUE TITLE
Nyancat Testnet v0.14 Results

### ISSUE THREAD

**Issue by julia2804** [irisnet/testnets#293]
Thanks everyone for your participation.

In summary, 55 community members have submitted the [form](http://nyancat-irisnet.mikecrm.com/SnqhRqw). Someone who has not finish the task 1, please follow this [doc](https://github.com/irisnet/testnets/tree/master/nyancat) to start your node correctly by using the right formatted moniker which the [doc](https://github.com/irisnet/testnets/tree/master/nyancat/v0.14) describes.

Thanks again to everyone for your cooperation, we decided to lower the threshold of Task 2, the validators who participated in the consensus in the first **300** blocks of nyancat-2 will receive the rewards !

Here are some details for Nyancat, if your information isn't listed, please contact us anytime:

|        |                                      |                                                 | Task 1                                                       |          |                                | Task 2                                   |          | Task 3   |
| ------ | ------------------------------------ | ----------------------------------------------- | ------------------------------------------------------------ | -------- | ------------------------------ | ---------------------------------------- | -------- | -------- |
| Number | Github ID                            | PGP ID                                          | Link                                                         | Complete | Note                           | Validator Address                        | Complete | Complete |
| 1      | <https://github.com/iammelea>        | 4BE49EABAA41B8BF                                | <http://144.217.215.73:26657/status>                         | 1        |                                | DDCADD63C7805B68D861C1C84F0819A7260C8B1E | 1        | 0        |
| 2      | <https://github.com/jim380>          | 5CCA4F526B9F85DA                                | <http://144.202.105.89:26657/status>                         | 0        |                                | 34FC7ED69C6DF8D0D5A6CC674E0068A92240699B | 0        | 0        |
| 3      | <https://github.com/shiknian>        | F1F0BF192D84EAC3                                | <http://112.124.202.66:26657/status>                         | 1        |                                | BF84BC1334E698E628B061E729B384DC0192F08E | 1        | 1        |
| 4      | <https://github.com/kwunyeung>       | 3B84437810397048                                | <http://34.80.119.184:26657/status>                          | 1        |                                | F8916077A13ED7D7FF3CCFB779BF6904A99CFC59 | 1        | 0        |
| 5      | <https://github.com/wjdfx>           | 1A221528C4EE864E                                | <http://172.96.225.241:36657/status>                         | 1        | Using a non-conformant moniker |                                          | 0        | 1        |
| 6      | <https://github.com/cachitu>         | 909A480D5643CCC5                                | <http://node01.ip.sx:26657/status>                           | 0        | Submmited ip of wrong network  |                                          | 0        | 0        |
| 7      | <https://github.com/chinezupwnz>     | 2C877AC873132C91                                | <http://80.241.217.149:26657/status>                         | 1        |                                | F85D2B404E296373C4B89F16016B450A7178E0B5 | 1        | 1        |
| 8      | <https://github.com/mattharrop>      | 60C1D5AF5EE3F736                                | <http://54.39.190.89:26657/status>                           | 1        |                                | 5254D6074050579B2DD9590AAA011D8D0AE56712 | 1        | 0        |
| 9      | <https://github.com/andrewpaulicek>  | F21617F87E6DAF2A                                | <http://3.122.165.228:26657/status>                          | 1        |                                | 40CA0D1A2B865CF86F5B8C8A30EF4D74C635F02B | 1        | 1        |
| 10     | <https://github.com/natemiller1>     | 30DBAA0F6C67E4CE                                | <http://3.18.97.182:26657/status>                            | 1        |                                | 680E86937D5FC90E8BD61772C2BDD08AA40FF858 | 0        | 0        |
| 11     | <https://github.com/yulidai>         | 53CF46B650F9A40E742163F8D57BF05F937019EC        | <http://120.26.49.95:26657/status>                           | 0        |                                |                                          |          | 0        |
| 12     | <https://github.com/qq1206676756>    | 6C2175C3893D9572                                | <http://106.12.137.32:26657/status>                          | 1        |                                | 638A01DFB2FF7A01FEE1131AE3699F8948D4F090 | 1        | 1        |
| 13     | <https://github.com/POSBakerz>       | 3AFAE7268F4DFD10                                | <http://35.246.116.230:26657/status>                         | 1        |                                | EC7D5A4BD040652F4A4F24B724E7AAFA2FAA69B4 | 0        | 0        |
| 14     | <https://github.com/louisw420>       | C1FA4BA040797529                                | <http://140.82.43.113:26657/status>                          | 1        | Using a non-conformant moniker | CE9FAE883F33A007F716C850FFE824B36B83136F | 0        | 0        |
| 15     | <https://github.com/chainlayer>      | AD3CDBC91802F94A                                | <http://167.71.12.153:26657/status>                          | 1        |                                | CEC166CE41E805D605ED4AFE335889C0FA02FD93 | 1        | 1        |
| 16     | <https://github.com/chris-remus>     | 81D443FA08A4A926                                | <http://172.104.128.129:26657/status>                        | 1        |                                | 355D1425BBDFB44BAAA258052AF4B9E43C4BE954 | 1        | 0        |
| 17     | <https://github.com/kvdv80>          | ASAdBJThzkdboP90vu77pxOO80nnu_rFcR_5vnJp12CNbQo | <http://85.214.113.186:26657/status>                         | 0        |                                |                                          | 0        | 0        |
| 18     | <https://github.com/keystore-com>    | 749F98409D48C495                                | <http://847.52.27.73:26657/status>                           | 1        | Using a non-conformant moniker | 927341A729DCF194291C3335041B6ECF36B1B3DD | 0        | 0        |
| 19     | <https://github.com/wukong5>         | 9A26C5A2EE8EAFD2                                | <http://106.15.47.168:26657/status>                          | 1        |                                | 8CD8D4F78D5C19099AE12684F95C4EDCE2C394F0 | 1        | 1        |
| 20     | <https://github.com/weiwenlong555>   | DE22EF4D75849301A5283B143B702801F00074AF        | <http://47.88.159.6:26657/status>                            | 0        |                                |                                          | 0        | 1        |
| 21     | <https://github.com/kestop>          | A21D897660B856AC                                | <http://103.25.200.170:26657/status>                         | 0        |                                |                                          | 0        | 0        |
| 22     | <https://github.com/phantomk>        | A386B9E0D012C36CB36B671DBF4B1C55A2B62090        | <http://172.81.210.148:26657/status>                         | 0        |                                |                                          | 0        | 0        |
| 23     | <https://github.com/yn-alex>         | FAA52713CBDB55F7                                | <http://207.180.217.33:26657/status>                         | 1        |                                | CAA2D43BFA31C2E9BF9D83B433E6157547A2130E | 1        | 1        |
| 24     | <https://github.com/TomWang10>       | 72AD87997F28D5B8                                | <http://47.102.203.199:26657/status>                         | 1        |                                | CD6520518F7A1E7E561A17DFF9B924C6D333FA84 | 1        | 1        |
| 25     | <https://github.com/NodeATeam>       | B700C93D9E4578F666108BE80CB9A4E7643FF992        | <http://13.56.7.82:26657/status>                             | 1        |                                | B27194F8EFED98BBDA74A7A4E2C62728331A3747 | 1        | 1        |
| 26     | <https://github.com/neo4l>           | 4F8A0143E0C438C1                                | <http://52.221.222.218:26657/status>                         | 1        |                                | 3C2FB9684EF3DCA70EFB0EE2D7A6A9D9D0E4ABED | 1        | 1        |
| 27     | <https://github.com/ABEF>            | BE46BDB610AAB0EA                                | <http://34.90.202.50:26657/status>                           | 0        |                                |                                          | 0        | 0        |
| 28     | <https://github.com/KunPengRen>      | 65909B956DF0F488                                | <http://47.95.8.12:26657/status>                             | 1        |                                | 747447D63FE184DF0B3BD77B1D043EA04968E740 | 1        | 1        |
| 29     | <https://github.com/trevorfu>        | 970C963A17D00645                                | <http://159.138.238.167:26657/status>                        | 1        |                                | 44C6CF8518ACC056A3A6202A6AE17A075F2F8C83 | 1        | 1        |
| 30     | <https://github.com/abouzidi>        | BE448F9ECAB40ABE                                | <http://144.202.83.235:26657/status>                         | 1        |                                | 75875F70948E33D1650B9692EF1C51FF3A57DF88 | 1        | 1        |
| 31     | <https://github.com/dafricash>       | 0E8CF907E0FD833F116880F95281C9C7BE5C2646        | <http://95.179.137.7:26657/status>                           | 1        |                                | 426F337F3FB2E411B35A4F5A12009B3CF5D61BB4 | 1        | 1        |
| 32     | <https://github.com/wetezos>         | 26FA2B24F46A98EF                                | <http://52.76.43.33:26657/status>                            | 1        |                                | D760FD26F325561644BF6301B0C20149146CE14E | 0        | 1        |
| 33     | <https://github.com/UbikCapital>     | 8265DEAF50B61DF7                                | <http://167.86.115.5:26657/status>                           | 0        |                                |                                          | 0        | 0        |
| 34     | <https://github.com/warren666>       | 27DB3C341EFE27F0                                | <http://129.28.168.114:26657/status>                         | 1        |                                | C309CCBCC15ED3597F7DB42CCEF9A4D720CE2B9D | 1        | 0        |
| 35     | <https://github.com/julia2804>       | 117C130C833C1B37                                | <http://34.80.218.185:26657/status>                          | 1        |                                |                                          | 0        | 0        |
| 36     | <https://github.com/dolphintwo>      | 7A38C8CD6C0FA32A                                | <http://122.152.221.126:26657/status>                        | 0        |                                |                                          | 0        | 0        |
| 37     | <https://github.com/LiangLiang918>   | DBF3F5B2CA263BF2                                | <http://106.15.234.17:26657/status>                          | 1        |                                | B8152C832A65665B68B33E45B5A5FCED30A03971 | 1        | 1        |
| 38     | <https://github.com/CrazySnailNO001> | CF242D961E36802A                                | <http://106.14.148.58:26657/status>                          | 1        |                                | 75548B700A6E47F3B4290403C07E8586EDF2D6FA | 1        | 1        |
| 39     | <https://github.com/oncloudit>       | 1E70794B56DFB583                                | <http://115.28.65.150:26657/status>                          | 1        |                                | 0DF1CD84F0A01D43D396FA510A3975BDA4B4270E | 1        | 1        |
| 40     | <https://github.com/rich518>         | 3A7A52FC729AE13F                                | <http://118.31.124.205:26657/status>                         | 1        | Using a non-conformant moniker | 3448C1FA4116C11A82018AEB0F44A4EF953E6E75 | 1        | 1        |
| 42     | <https://github.com/kvdv80>          | F898ACE263EC1C4E                                | <http://164.68.96.165:26657/status>                          | 1        |                                | 36B0C2BC6853E51E929256FEAC9B6BEAAC7B3F83 | 1        | 1        |
| 43     | https://github.com/vistwang          | D73D632ACC76163D                                | http://47.98.213.120:26657/status                            | 1        |                                | 27D7F3933D1D8A01762B32C1FF3ED44B99425B5A | 1        | 1        |
| 44     | https://github.com/huanglei579       | 97D37B65EC38BAC8                                | <http://3.130.229.213:26657/status>                          | 1        |                                | 0EA8D5FF76F6A649446646DD3717BFA3E3BD2859 | 1        | 1        |
| 45     | https://github.com/shuke0327         | DA4CF56ADE526129                                | <http://13.59.165.223:26657/status>                          | 1        |                                | BB7142DC79867A4B3D60B80961B7345E55E96951 | 1        | 1        |
| 46     | https://github.com/mahuaibo          | 9B75D5E7320419BB                                | [http://47.254.32.219:26657/status](http://47.254.32.219:26657/status) | 1        |                                | 2FB469B7AF215F621E90FE596E9BAE971850627D | 0        | 1        |
| 47     | https://github.com/luckybean         | 8E15046A255C20CC                                | [http://15.164.38.177:26657/status](http://15.164.38.177:26657/status) | 0        | Using a non-conformant moniker | 7211BFF5B79ED59152D3E2E74D90080D6637BF6C | 1        | 1        |
| 48     | https://github.com/imnisen           | 718F9BE7EBD5DE59                                | [http://34.74.195.236:26657/status](http://34.74.195.236:26657/status) | 1        |                                |                                          | 0        | 0        |
| 49     | https://github.com/ponchik69         | E12F4695036D8072                                | <http://116.203.73.37:26657/status>                          | 0        |                                |                                          | 0        | 1        |
| 50     | https://github.com/liangping         | 6EA723DA332200B2                                | [http://47.245.57.97:26657/status](http://47.245.57.97:26657/status) | 1        |                                |                                          | 0        | 1        |
| 51     | https://github.com/i7495             | CE335B8803B8898E                                | [http://94.237.40.220:26657/status](http://94.237.40.220:26657/status) | 1        |                                |                                          | 0        | 1        |
| 52     | https://github.com/marx2019          | C8083472E22D5476                                | [http://123.56.6.206:26657/status](http://123.56.6.206:26657/status) | 0        | New github account             |                                          | 0        | 0        |
| 53     | https://github.com/wuyunjiao         | 553D2D5BAC15E8B8                                | [http://47.244.104.173:26657/status](http://47.244.104.173:26657/status) | 0        | New github account             |                                          | 0        | 1        |
| 54     | https://github.com/mayt613           | 3EDC046A95C6D3D3                                | [http://182.50.125.85:26657/status](http://182.50.125.85:26657/status) | 0        |                                |                                          | 0        | 1        |
| 55     | https://github.com/Steepouyang       | F09FF586F5000416                                | [http://54.180.3.66:26657/status](http://54.180.3.66:26657/status) | 1        |                                |                                          | 0        | 1        |

**Comment by kwunyeung** [comment]
Please update our IP address. Thanks!

http://34.80.119.184:26657/status

**Comment by kvdv80** [comment]
Please also update our ip address:
https://github.com/kvdv80 
New address: 164.68.96.165
(http://164.68.96.165:26657/status)

Thanks!

**Comment by mahuaibo** [comment]
Please update our IP address. Thanks!

http://47.244.104.173:26657

**Comment by wuyunjiao** [comment]
Please update our IP address. Thanks!

http://47.254.32.219:26657/status

**Comment by marx2019** [comment]
Please update our IP address. 

123.56.6.206:26657

Thanks!

**Comment by dolphintwo** [comment]
please update my pgp-id 
7A38C8CD6C0FA32A
Thanks!

**Comment by zhangyelong** [comment]
> Please update our IP address. Thanks!
> 
> http://47.244.104.173:26657/status

Please submit your informations to this form: http://nyancat-irisnet.mikecrm.com/SnqhRqw

**Comment by zhangyelong** [comment]
> Please update our IP address.
> 
> 123.56.6.206:26657
> 
> Thanks!

Please submit your informations to this form: http://nyancat-irisnet.mikecrm.com/SnqhRqw

**Comment by wuyunjiao** [comment]
> > Please update our IP address. Thanks!
> > http://47.244.104.173:26657/status
> 
> Please submit your informations to this form: http://nyancat-irisnet.mikecrm.com/SnqhRqw

Submit completed

**Comment by marx2019** [comment]
> > Please update our IP address.
> > 123.56.6.206:26657
> > Thanks!
> 
> Please submit your informations to this form: http://nyancat-irisnet.mikecrm.com/SnqhRqw

Submited

**Comment by i7495** [comment]
Hi. I just filled the form. Please add our node to the table if it is possible http://94.237.40.220:26657/status

**Comment by wukong5** [comment]
Hi,i have changed my ip address from http://47.111.20.50:26657/status to http://106.15.47.168:26657/status,please help me to change in the form.thanks

**Comment by imnisen** [comment]
Please also update our ip address:
https://github.com/imnisen
Old address: 34.74.195.236
New address: 35.236.194.234 
(http://35.236.194.234:26657/status)

Thanks!
