### ISSUE TITLE
Nyancat Testnet v0.15 Results

### ISSUE THREAD

**Issue by zhangyelong** [irisnet/testnets#299]
Thanks everyone for your participation.

For new validators, please remember to submit this [form](http://nyancat-irisnet.mikecrm.com/SnqhRqw), then start your validator node and set your validator moniker to `<your-name>-<pgp-id>`, identity to `<pgp-id>`.

**Task Verification**

Task 1:  [Note: Only `native token` is valid] 

https://nyancat.bigdipper.live/account/faa1jpuzrxtu346pae9szdk9thumaxxew740w8w3an

Task 2: [Note: Only `gateway token` is valid] 

https://nyancat.bigdipper.live/account/faa1jmm8fa63ncsphk29e5wj6jy56tea9zz2y202mn

Task 3 [[online test](https://jqplay.org/s/GWn_IEuyAy)]:

```bash
# download mint txs
curl -o mint.json http://34.80.154.59:1317/txs?action=mint_token&recipient=faa1cnm7zenktxuhksxx3vj3e78cux98rrh28y4tcd

# sort by timestamp -> filter success txs -> query asset owners
jq 'sort_by(.timestamp) | map(select(.result.Code == 0)) | .[].tx.value.msg[0].value.owner' mint.json
```

Task 4 [[online test](https://jqplay.org/s/QfPXOe20Ex)]:

```bash
# download burn txs
curl -o burn.json http://34.80.154.59:1317/txs?action=burn

# sort by timestamp -> filter success txs -> filter !iris txs -> query asset owners
jq 'sort_by(.timestamp) | map(select(.result.Code == 0)) | map(select(.tx.value.msg[0].value.coins[0].denom != "iris-atto")) | .[].tx.value.msg[0].value.owner' burn.json
```

Task 5 [[online test](https://jqplay.org/s/7JSSbYF32N)]:

```bash
# download transfer_token_owner txs
curl -o transfer_token_owner.json http://34.80.154.59:1317/txs?action=transfer_token_owner

# sort by timestamp -> filter success txs -> filter dst_owner -> query asset original owners
jq 'sort_by(.timestamp) | map(select(.result.Code == 0)) | map(select(.tx.value.msg[0].value.dst_owner == "faa14sk203d2akh96gdlhveglw5emfpf0h8xqls3l0")) | .[].tx.value.msg[0].value.src_owner' transfer_token_owner.json
```

Task 6 [[verify.sh](https://github.com/irisnet/testnets/blob/master/nyancat/v0.15/task-6/verify.sh)]

```bash
curl -s https://raw.githubusercontent.com/irisnet/testnets/master/nyancat/v0.15/task-6/verify.sh | sh
```

Task 7 [[verify.sh](https://github.com/irisnet/testnets/blob/master/nyancat/v0.15/task-7/verify.sh)]

```bash
git clone https://github.com/irisnet/testnets
cd testnets/nyancat/v0.15/task-7
sh verify.sh
```

Task 8 [[verify.sh](https://github.com/irisnet/testnets/blob/master/nyancat/v0.15/task-8/verify.sh)]

```bash
curl -s https://raw.githubusercontent.com/irisnet/testnets/master/nyancat/v0.15/task-8/verify.sh | bash
```

**Note**: For every task, only the top 40 validators who completes can get rewards, e.g. if someone only complete task 1 in top 40, he will get the only rewards of task 1

Here are some details of v0.15, if your information isn't listed correctly, please contact us anytime:

| Profiles |                                      |                                                 |                                          |                                                              |                    | Task 1                                                       | Task 2                                                       | Task 3                             | Task 4                             | Task 5                             | Task 6                               | Task 7                               | Task 8                               |
| -------- | ------------------------------------ | ----------------------------------------------- | ---------------------------------------- | ------------------------------------------------------------ | ------------------ | ------------------------------------------------------------ | ------------------------------------------------------------ | ---------------------------------- | ---------------------------------- | ---------------------------------- | ------------------------------------ | ------------------------------------ | ------------------------------------ |
| Number   | Github ID                            | PGP ID                                          | Validator Address                        | Account  Address                                             | Note               | Complete:40<br>[Latest](https://nyancat.bigdipper.live/transactions/6AE413E3DCBF9D55B25EDCACA048EC73457513D61FAB513EF345392645E82D06) | Complete: 40<br>[Latest](https://nyancat.bigdipper.live/transactions/36466A5AD2A30843B9EA883FA406F02A19018BE976276BFBE248AE6046A9B06E) | Complete:40<br>Latest Height:24250 | Complete:40<br>Latest Height:65445 | Complete:40<br>Latest Height:24471 | Complete:40<br/>Latest Height:293216 | Complete:36<br/>Latest Height:293368 | Complete:33<br/>Latest Height:52300 |
| 1        | <https://github.com/iammelea>        | 4BE49EABAA41B8BF                                | DDCADD63C7805B68D861C1C84F0819A7260C8B1E | [faa1v7uavt9xg6zauey4r7xsssa2xnsl3mvdjkdf5c](https://nyancat.bigdipper.live/account/faa1v7uavt9xg6zauey4r7xsssa2xnsl3mvdjkdf5c) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 2        | <https://github.com/jim380>          | 5CCA4F526B9F85DA                                | 34FC7ED69C6DF8D0D5A6CC674E0068A92240699B | [faa1c68vad2tcrvh87dxdsf6vnjk52zlvu7cfexsxs](https://nyancat.bigdipper.live/account/faa1c68vad2tcrvh87dxdsf6vnjk52zlvu7cfexsxs) |                    |                                                              |                                                              | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 3        | <https://github.com/shiknian>        | F1F0BF192D84EAC3                                | BF84BC1334E698E628B061E729B384DC0192F08E | [faa1f64m50kuemuwfeztpa8mnju309n434anvyx8y3](https://nyancat.bigdipper.live/account/faa1f64m50kuemuwfeztpa8mnju309n434anvyx8y3) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 4        | <https://github.com/kwunyeung>       | 3B84437810397048                                | F8916077A13ED7D7FF3CCFB779BF6904A99CFC59 | [faa1j5yvdxyf5t6ngtulq0fqvkmzumxchn3xd4tu33](https://nyancat.bigdipper.live/account/faa1j5yvdxyf5t6ngtulq0fqvkmzumxchn3xd4tu33) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    |                                      |  |
| 5        | <https://github.com/wjdfx>           | 1A221528C4EE864E                                |                                          | [faa1tlz4l9jvrrne6wduk34099jq524yre4qx6xazr](https://nyancat.bigdipper.live/account/faa1tlz4l9jvrrne6wduk34099jq524yre4qx6xazr) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 6        | <https://github.com/cachitu>         | 909A480D5643CCC5                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 7        | <https://github.com/chinezupwnz>     | 2C877AC873132C91                                | F85D2B404E296373C4B89F16016B450A7178E0B5 | [faa1cn2q6840090kgkpdyl330x5css5kp7m4xsw0c4](https://nyancat.bigdipper.live/account/faa1cn2q6840090kgkpdyl330x5css5kp7m4xsw0c4) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 8        | <https://github.com/mattharrop>      | 60C1D5AF5EE3F736                                | 5254D6074050579B2DD9590AAA011D8D0AE56712 | [faa1pkjw2ejkdyc33nde89yfh0jvppd59knlpx2ppj](https://nyancat.bigdipper.live/account/faa1pkjw2ejkdyc33nde89yfh0jvppd59knlpx2ppj) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 9        | <https://github.com/andrewpaulicek>  | F21617F87E6DAF2A                                | 40CA0D1A2B865CF86F5B8C8A30EF4D74C635F02B | [faa1mulwqur6vtnqrlf9cr5z5rw78wxq0ahptysqsd](https://nyancat.bigdipper.live/account/faa1mulwqur6vtnqrlf9cr5z5rw78wxq0ahptysqsd) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 10       | <https://github.com/natemiller1>     | 30DBAA0F6C67E4CE                                | 680E86937D5FC90E8BD61772C2BDD08AA40FF858 |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 11       | <https://github.com/yulidai>         | 53CF46B650F9A40E742163F8D57BF05F937019EC        |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 12       | <https://github.com/qq1206676756>    | 6C2175C3893D9572                                | 638A01DFB2FF7A01FEE1131AE3699F8948D4F090 | [faa1980ssuj97gt4gsv6zu9sch804pn4rl6f7as2gz](https://nyancat.bigdipper.live/account/faa1980ssuj97gt4gsv6zu9sch804pn4rl6f7as2gz) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 13       | <https://github.com/POSBakerz>       | 3AFAE7268F4DFD10                                | EC7D5A4BD040652F4A4F24B724E7AAFA2FAA69B4 | [faa18vr8xwzr6wynsnr8x3cd7e2ezs9d0lvzkuwxam](https://nyancat.bigdipper.live/account/faa18vr8xwzr6wynsnr8x3cd7e2ezs9d0lvzkuwxam) |                    | 1                                                            | 1                                                            | 1                                  |                                    | 1                                  | 1                                    | 1                                    | 1 |
| 14       | <https://github.com/louisw420>       | C1FA4BA040797529                                | CE9FAE883F33A007F716C850FFE824B36B83136F |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 15       | <https://github.com/chainlayer>      | AD3CDBC91802F94A                                | CEC166CE41E805D605ED4AFE335889C0FA02FD93 | [faa1dtrv4mn70qvwqqm4grgu3wd2ngxy0up9h2hl8g](https://nyancat.bigdipper.live/account/faa1dtrv4mn70qvwqqm4grgu3wd2ngxy0up9h2hl8g) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  |                                      |                                      | 1                                  |
| 16       | <https://github.com/chris-remus>     | 81D443FA08A4A926                                | 355D1425BBDFB44BAAA258052AF4B9E43C4BE954 |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    | 1                                    | 1                                    | 1                                  |
| 17       | <https://github.com/kvdv80>          | ASAdBJThzkdboP90vu77pxOO80nnu_rFcR_5vnJp12CNbQo |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 18       | <https://github.com/keystore-com>    | 749F98409D48C495                                | 927341A729DCF194291C3335041B6ECF36B1B3DD | [faa1g6a6k3ws9p94qndgkm0j39jyddx2k0yhc0t7yr](https://nyancat.bigdipper.live/account/faa1g6a6k3ws9p94qndgkm0j39jyddx2k0yhc0t7yr) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  |                                      |                                      | 1 |
| 19       | <https://github.com/wukong5>         | 9A26C5A2EE8EAFD2                                | 8CD8D4F78D5C19099AE12684F95C4EDCE2C394F0 | [faa1xc7gqn6d0xcg86ufzefpnrjjcwpxvwmqlskrfq](https://nyancat.bigdipper.live/account/faa1xc7gqn6d0xcg86ufzefpnrjjcwpxvwmqlskrfq) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 20       | <https://github.com/weiwenlong555>   | DE22EF4D75849301A5283B143B702801F00074AF        | 92F1178844A66685512DB9EC039D0642017AABAE | [faa179rglnwm7cezjhzfagcp3vz2vf6f6q4ps2x584](https://nyancat.bigdipper.live/account/faa179rglnwm7cezjhzfagcp3vz2vf6f6q4ps2x584) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 21       | <https://github.com/kestop>          | A21D897660B856AC                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 22       | <https://github.com/phantomk>        | A386B9E0D012C36CB36B671DBF4B1C55A2B62090        |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 23       | <https://github.com/yn-alex>         | FAA52713CBDB55F7                                | CAA2D43BFA31C2E9BF9D83B433E6157547A2130E | [faa1ygq0eqeaxmgmrqvxm7cvthpgsj7punake9funw](https://nyancat.bigdipper.live/account/faa1ygq0eqeaxmgmrqvxm7cvthpgsj7punake9funw) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 24       | <https://github.com/TomWang10>       | 72AD87997F28D5B8                                | CD6520518F7A1E7E561A17DFF9B924C6D333FA84 | [faa127lpsq4g8r0dhpk06w9le7yvp9axrkp80cuqxe](https://nyancat.bigdipper.live/account/faa127lpsq4g8r0dhpk06w9le7yvp9axrkp80cuqxe) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 25       | <https://github.com/NodeATeam>       | B700C93D9E4578F666108BE80CB9A4E7643FF992        | B27194F8EFED98BBDA74A7A4E2C62728331A3747 | [faa10mljgcjf9h2dq6fnms7pxfx8288mtw04a05wsa](https://nyancat.bigdipper.live/account/faa10mljgcjf9h2dq6fnms7pxfx8288mtw04a05wsa) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 26       | <https://github.com/neo4l>           | 4F8A0143E0C438C1                                | 3C2FB9684EF3DCA70EFB0EE2D7A6A9D9D0E4ABED | [faa1g6d8pczhth3960qvdht7sgvv0d6yst4u9evs0c](https://nyancat.bigdipper.live/account/faa1g6d8pczhth3960qvdht7sgvv0d6yst4u9evs0c) |                    |                                                              |                                                              |                                    | 1                                  |                                    | 1                                    | 1                                    | 1                                  |
| 27       | <https://github.com/ABEF>            | BE46BDB610AAB0EA                                |                                          |                                                              |                    | 1                                                            |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 28       | <https://github.com/KunPengRen>      | 65909B956DF0F488                                | 747447D63FE184DF0B3BD77B1D043EA04968E740 | [faa1tmy3x72wjgwktdr8h3axggpq4qsc03gwajag4d](https://nyancat.bigdipper.live/account/faa1tmy3x72wjgwktdr8h3axggpq4qsc03gwajag4d) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 29       | <https://github.com/trevorfu>        | 970C963A17D00645                                | 44C6CF8518ACC056A3A6202A6AE17A075F2F8C83 | [faa16fzh2wt75v0jekj5xd5qw25yz8qu82swdddqg5](https://nyancat.bigdipper.live/account/faa16fzh2wt75v0jekj5xd5qw25yz8qu82swdddqg5) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 30       | <https://github.com/abouzidi>        | BE448F9ECAB40ABE                                | 75875F70948E33D1650B9692EF1C51FF3A57DF88 | [faa1n5tqycmf8kyagatk9yyadd79e0cw4mldcm6w93](https://nyancat.bigdipper.live/account/faa1n5tqycmf8kyagatk9yyadd79e0cw4mldcm6w93) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 31       | <https://github.com/dafricash>       | 0E8CF907E0FD833F116880F95281C9C7BE5C2646        | 426F337F3FB2E411B35A4F5A12009B3CF5D61BB4 | [faa1azw5v7ncacsuavpdnkv8xt4w0pk85c4dd6h0js](https://nyancat.bigdipper.live/account/faa1azw5v7ncacsuavpdnkv8xt4w0pk85c4dd6h0js) |                    |                                                              | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 32       | <https://github.com/wetezos>         | 26FA2B24F46A98EF                                | D760FD26F325561644BF6301B0C20149146CE14E | [faa1cmjatace08q6yqs67m0rg7venyy93nary4t8hg](https://nyancat.bigdipper.live/account/faa1cmjatace08q6yqs67m0rg7venyy93nary4t8hg) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 33       | <https://github.com/UbikCapital>     | 8265DEAF50B61DF7                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 34       | <https://github.com/warren666>       | 27DB3C341EFE27F0                                | C309CCBCC15ED3597F7DB42CCEF9A4D720CE2B9D | [faa1jv4u9n5axk4ksmz8g844m8lhhespex22zy0s73](https://nyancat.bigdipper.live/account/faa1jv4u9n5axk4ksmz8g844m8lhhespex22zy0s73) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 35       | <https://github.com/julia2804>       | 117C130C833C1B37                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 36       | <https://github.com/dolphintwo>      | 7A38C8CD6C0FA32A                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 37       | <https://github.com/LiangLiang918>   | DBF3F5B2CA263BF2                                | B8152C832A65665B68B33E45B5A5FCED30A03971 | [faa1dcrenyng5kzdudnly8u9ahsdjmmmmzvmg0g2rd](https://nyancat.bigdipper.live/account/faa1dcrenyng5kzdudnly8u9ahsdjmmmmzvmg0g2rd) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 38       | <https://github.com/CrazySnailNO001> | CF242D961E36802A                                | 75548B700A6E47F3B4290403C07E8586EDF2D6FA | [faa146ems2u8y99nrg07le8h4j2g6s0yfx62nk20k2](https://nyancat.bigdipper.live/account/faa146ems2u8y99nrg07le8h4j2g6s0yfx62nk20k2) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    |                                      | 1                                  |
| 39       | <https://github.com/oncloudit>       | 1E70794B56DFB583                                | 0DF1CD84F0A01D43D396FA510A3975BDA4B4270E | [faa19q9qsghexglgekey9kzxgtt902yjel2rkfv37q](https://nyancat.bigdipper.live/account/faa19q9qsghexglgekey9kzxgtt902yjel2rkfv37q) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 40       | <https://github.com/rich518>         | 3A7A52FC729AE13F                                | 3448C1FA4116C11A82018AEB0F44A4EF953E6E75 | [faa1srueah6lvjyze3destavduv6ck7cvz6xfw6uhm](https://nyancat.bigdipper.live/account/faa1srueah6lvjyze3destavduv6ck7cvz6xfw6uhm) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 42       | <https://github.com/kvdv80>          | F898ACE263EC1C4E                                | 36B0C2BC6853E51E929256FEAC9B6BEAAC7B3F83 | [faa1est0jnntmeu8g6yv99vaa0khlmm478ajmhkkn4](https://nyancat.bigdipper.live/account/faa1est0jnntmeu8g6yv99vaa0khlmm478ajmhkkn4) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 43       | https://github.com/vistwang          | D73D632ACC76163D                                | 27D7F3933D1D8A01762B32C1FF3ED44B99425B5A | [faa17sp5jlwq0lgqaxdy43u000ycv04skfca9plkpn](https://nyancat.bigdipper.live/account/faa17sp5jlwq0lgqaxdy43u000ycv04skfca9plkpn) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    |                                      | 1                                  |
| 44       | https://github.com/huanglei579       | 97D37B65EC38BAC8                                | 0EA8D5FF76F6A649446646DD3717BFA3E3BD2859 | [faa1r4k9d89rjkfav5uwwtqxv6yelp3aschpk70w63](https://nyancat.bigdipper.live/account/faa1r4k9d89rjkfav5uwwtqxv6yelp3aschpk70w63) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    |                                      |                                    |
| 45       | https://github.com/shuke0327         | DA4CF56ADE526129                                | BB7142DC79867A4B3D60B80961B7345E55E96951 | [faa10qrr3685dsdwwvf6l0e9crawlvkzd9uy55ushf](https://nyancat.bigdipper.live/account/faa10qrr3685dsdwwvf6l0e9crawlvkzd9uy55ushf) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 46       | https://github.com/mahuaibo          | 9B75D5E7320419BB                                | 2FB469B7AF215F621E90FE596E9BAE971850627D | [faa1nnvjspdf7x6ra09q6gs8gqvkvkk4uz3lr48v64](https://nyancat.bigdipper.live/account/faa1nnvjspdf7x6ra09q6gs8gqvkvkk4uz3lr48v64) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    |                                    |
| 47       | https://github.com/luckybean         | 8E15046A255C20CC                                | 7211BFF5B79ED59152D3E2E74D90080D6637BF6C | [faa1rdeykzueahnall9nf3uryqxmhya85n6v5nlsu3](https://nyancat.bigdipper.live/account/faa1rdeykzueahnall9nf3uryqxmhya85n6v5nlsu3) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1                                  |
| 48       | https://github.com/imnisen           | 718F9BE7EBD5DE59                                |                                          | [faa1gstesvwarf0ftmeszx0tjhfwxrlvzclktlkvvq](https://nyancat.bigdipper.live/account/faa1gstesvwarf0ftmeszx0tjhfwxrlvzclktlkvvq) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 49       | https://github.com/ponchik69         | E12F4695036D8072                                |                                          |                                                              |                    | 1                                                            |                                                              |                                    |                                    |                                    |                                      |                                      |  |
| 50       | https://github.com/liangping         | 6EA723DA332200B2                                |                                          | [faa14euxqx4qzyk82908ehktyxdgta5yzuhmlk6zlk](https://nyancat.bigdipper.live/account/faa14euxqx4qzyk82908ehktyxdgta5yzuhmlk6zlk) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 51       | https://github.com/i7495             | CE335B8803B8898E                                |                                          | [faa18wvfx7j783wq7v6dkr3mjfna2s2ul3d5r6z3pz](https://nyancat.bigdipper.live/account/faa18wvfx7j783wq7v6dkr3mjfna2s2ul3d5r6z3pz) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 52       | https://github.com/marx2019          | C8083472E22D5476                                |                                          |                                                              | New github account |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 53       | https://github.com/wuyunjiao         | 553D2D5BAC15E8B8                                |                                          | [faa1jwu4njhr4njrtdclcf9ctjqx00axe5gfv9dcsc](https://nyancat.bigdipper.live/account/faa1jwu4njhr4njrtdclcf9ctjqx00axe5gfv9dcsc) | New github account | ~~1~~                                                        | ~~1~~                                                        | ~~1~~                              | ~~1~~                              | ~~1~~                              | ~~1~~                                | ~~1~~                                |                                    |
| 54       | https://github.com/mayt613           | 3EDC046A95C6D3D3                                |                                          | [faa1a48f3glf5wrlztpjt5vr9sp0f93p8eef285jxk](https://nyancat.bigdipper.live/account/faa1a48f3glf5wrlztpjt5vr9sp0f93p8eef285jxk) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 55       | https://github.com/Steepouyang       | F09FF586F5000416                                |                                          | [faa1qkfu7e58pqm30d4ak0gguhnqnx00r6t5v55np0](https://nyancat.bigdipper.live/account/faa1qkfu7e58pqm30d4ak0gguhnqnx00r6t5v55np0) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 56       | https://github.com/ABEF              | BE46BDB610AAB0EA                                |                                          | [faa1sax9q0ma3fyw2z8mu9y0wry0yayv4ecnu9zmls](https://nyancat.bigdipper.live/account/faa1sax9q0ma3fyw2z8mu9y0wry0yayv4ecnu9zmls) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  |                                      |                                      |                                    |
| 57       | https://github.com/cachitu           | 909A480D5643CCC5                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 58       | https://github.com/farss             | F54C3A22392847AEC1EE5AD601721119CAE76A9E        |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 59       | https://github.com/zhanglianghui     | 49D02A7526022E7C                                |                                          | [faa1hct7c2dwlfy6328nuumz7va59elf4c0a2dhl7v](https://nyancat.bigdipper.live/account/faa1hct7c2dwlfy6328nuumz7va59elf4c0a2dhl7v) |                    | 1                                                            | 1                                                            | 1                                  | 1                                  | 1                                  | 1                                    | 1                                    | 1 |
| 60       | https://github.com/eon0001           | D54C8032CF19C407                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      |                                    |
| 61       | https://github.com/samscau           | 70FA19B71FE14D20                                |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    | 1                                    | 1                                    |                                    |
| 62       | https://github.com/b-harvest         | BFAAF68BD473D23958D452708957C5091FBF4192        |                                          |                                                              |                    |                                                              |                                                              |                                    |                                    |                                    |                                      |                                      | 1 |

**Comment by eon0001** [comment]
I am unable to access the form https://nyancat-irisnet.mikecrm.com/SnqhRqw . Are there any geographical restrictions on this contest.?

**Comment by zhangyelong** [comment]
> I am unable to access the form https://nyancat-irisnet.mikecrm.com/SnqhRqw . Are there any geographical restrictions on this contest.?

I don't think so, but feel free to email me of your profile: yelong@bianjie.ai, I will add your profile to the list :)

**Comment by kwunyeung** [comment]
> I am unable to access the form https://nyancat-irisnet.mikecrm.com/SnqhRqw . Are there any geographical restrictions on this contest.?

Yes, I think it's something related to the GFW. I can't access it from Taiwan. VPN to somewhere else and try again.

**Comment by eon0001** [comment]
@zhangyelong @kwunyeung Thanks vpn worked for me

**Comment by dafricash** [comment]
Hello,
Can you please update my information with the following: 
pgp ID: 5281C9C7BE5C2646 
account address: faa1azw5v7ncacsuavpdnkv8xt4w0pk85c4dd6h0js
Thanks in advance

**Comment by yn-alex** [comment]
Hi,

Some time after I completed task 6 I noticed that I forgot to put the memo inside the TX. As a result, the PGP-ID does not appear on the first TX and I did it again so it can be confirmed it was me.

**TX where I forgot the memo:**
```
grep "D24649E790452744B0EBCA008FD9A3FBD8446E9F895859FDE0A5C0860D55C17F" -B 2 -A1 task6.results
    "PGP_ID": "",
    "height": "123400",
    "hash": "D24649E790452744B0EBCA008FD9A3FBD8446E9F895859FDE0A5C0860D55C17F",
    "timestamp": "2019-07-19T12:00:12Z"
```

**TX where I put the memo:**
```
grep "B15FDF3B56C421833FD2F78C1FD6CE39A675AAB85556AA40D1AB782DD2E8D5A6" -B 2 -A1 task6.results
    "PGP_ID": "FAA52713CBDB55F7",
    "height": "287726",
    "hash": "B15FDF3B56C421833FD2F78C1FD6CE39A675AAB85556AA40D1AB782DD2E8D5A6",
    "timestamp": "2019-07-31T11:56:12Z"
```

Hoping it can still be counted for the task6 reward. Thanks.
