### ISSUE TITLE
iriscli keys export Mykey  = Not ask for confirm password when encrypting

### ISSUE THREAD

**Issue by iammelea** [irisnet/testnets#336]
Hello, when want to create a new account ```Iris``` ask for confirm password after create the new account.
IMO have to be in the same way when ```iriscli keys export```

```
iriscli keys export Mykey --output-file=<path_to_backup_keystore>
```
where

```
iris:~$ iriscli keys export newmele --output-file=mele.json
Password to sign with 'newmele':
Password to sign the keystore file:
```
here is where I believe the  *user* need to confirm for be sure password is ok.
```Repeat the Password``` 
Example
```
iris:~$ iriscli keys export newmele --output-file=mele.json
Password to sign with 'newmele':
Password to sign the keystore file:
Repeat the Password:
```

That is, thanks

**Comment by zhangyelong** [comment]
Resolved
