### ISSUE TITLE
Nyancat Testnet Summary

### ISSUE THREAD

**Issue by zhangyelong** [irisnet/testnets#353]
# [How to claim rewards](https://github.com/irisnet/testnets/blob/master/nyancat/reward-claims/README.md)

| Profiles |                                    |                                           | Summary | v0.14  |        | v0.15  |        |        |        |        |        |        |        |
| -------- | ---------------------------------- | ----------------------------------------- | ------- | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ | ------ |
| Number   | Github ID                          | PGP ID                                    | Points  | Task 2 | Task 3 | Task 1 | Task 2 | Task 3 | Task 4 | Task 5 | Task 6 | Task 7 | Task 8 |
| 1        | https://github.com/iammelea        | 4BE49EABAA41B8BF                          | 300     | 200    | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 2        | https://github.com/jim380          | 5CCA4F526B9F85DA                          | 250     | 0      | 0      | 0      | 0      | 10     | 10     | 10     | 10     | 10     | 200    |
| 3        | https://github.com/shiknian        | F1F0BF192D84EAC3                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 4        | https://github.com/kwunyeung       | 3B84437810397048                          | 290     | 200    | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 0      | 0      |
| 5        | https://github.com/wjdfx           | 1A221528C4EE864E                          | 150     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| ~~6~~    | ~~https://github.com/cachitu~~     | Duplicate with NO.57 ~~909A480D5643CCC5~~ | ~~0~~   | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  |
| 7        | https://github.com/chinezupwnz     | 2C877AC873132C91                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 8        | https://github.com/mattharrop      | 60C1D5AF5EE3F736                          | 500     | 200    | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 9        | https://github.com/andrewpaulicek  | F21617F87E6DAF2A                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 10       | https://github.com/natemiller1     | 30DBAA0F6C67E4CE                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 11       | https://github.com/yulidai         | 53CF46B650F9A40E742163F8D57BF05F937019EC  | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 12       | https://github.com/qq1206676756    | 6C2175C3893D9572                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 13       | https://github.com/POSBakerz       | 3AFAE7268F4DFD10                          | 290     | 0      | 0      | 20     | 30     | 10     | 0      | 10     | 10     | 10     | 200    |
| 14       | https://github.com/louisw420       | C1FA4BA040797529                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 15       | https://github.com/chainlayer      | AD3CDBC91802F94A                          | 530     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 0      | 0      | 200    |
| 16       | https://github.com/chris-remus     | 81D443FA08A4A926                          | 420     | 200    | 0      | 0      | 0      | 0      | 0      | 0      | 10     | 10     | 200    |
| ~~17~~   | ~~https://github.com/kvdv80~~      | Duplicate with NO.42                      | ~~0~~   | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  |
| 18       | https://github.com/keystore-com    | 749F98409D48C495                          | 280     | 0      | 0      | 20     | 30     | 10     | 10     | 10     | 0      | 0      | 200    |
| 19       | https://github.com/wukong5         | 9A26C5A2EE8EAFD2                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 20       | https://github.com/weiwenlong555   | DE22EF4D75849301A5283B143B702801F00074AF  | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 21       | https://github.com/kestop          | A21D897660B856AC                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 22       | https://github.com/phantomk        | A386B9E0D012C36CB36B671DBF4B1C55A2B62090  | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 23       | https://github.com/yn-alex         | FAA52713CBDB55F7                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 24       | https://github.com/TomWang10       | 72AD87997F28D5B8                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 25       | https://github.com/NodeATeam       | B700C93D9E4578F666108BE80CB9A4E7643FF992  | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 26       | https://github.com/neo4l           | 4F8A0143E0C438C1                          | 480     | 200    | 50     | 0      | 0      | 0      | 10     | 0      | 10     | 10     | 200    |
| ~~27~~   | ~~https://github.com/ABEF~~        | Duplicate with NO.56                      | ~~0~~   | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  | ~~0~~  |
| 28       | https://github.com/KunPengRen      | 65909B956DF0F488                          | 350     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 29       | https://github.com/trevorfu        | 970C963A17D00645                          | 350     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 30       | https://github.com/abouzidi        | BE448F9ECAB40ABE                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 31       | https://github.com/dafricash       | 0E8CF907E0FD833F116880F95281C9C7BE5C2646  | 330     | 200    | 50     | 0      | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 32       | https://github.com/wetezos         | 26FA2B24F46A98EF                          | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 33       | https://github.com/UbikCapital     | 8265DEAF50B61DF7                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 34       | https://github.com/warren666       | 27DB3C341EFE27F0                          | 500     | 200    | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 35       | https://github.com/julia2804       | 117C130C833C1B37                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 36       | https://github.com/dolphintwo      | 7A38C8CD6C0FA32A                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 37       | https://github.com/LiangLiang918   | DBF3F5B2CA263BF2                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 38       | https://github.com/CrazySnailNO001 | CF242D961E36802A                          | 540     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 0      | 200    |
| 39       | https://github.com/oncloudit       | 1E70794B56DFB583                          | 350     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 40       | https://github.com/rich518         | 3A7A52FC729AE13F                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 42       | https://github.com/kvdv80          | F898ACE263EC1C4E                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 43       | https://github.com/vistwang        | D73D632ACC76163D                          | 540     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 0      | 200    |
| 44       | https://github.com/huanglei579     | 97D37B65EC38BAC8                          | 340     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 0      | 0      |
| 45       | https://github.com/shuke0327       | DA4CF56ADE526129                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 46       | https://github.com/mahuaibo        | 9B75D5E7320419BB                          | 150     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 0      |
| 47       | https://github.com/luckybean       | 8E15046A255C20CC                          | 550     | 200    | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 48       | https://github.com/imnisen         | 718F9BE7EBD5DE59                          | 300     | 0      | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 49       | https://github.com/ponchik69       | E12F4695036D8072                          | 70      | 0      | 50     | 20     | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 50       | https://github.com/liangping       | 6EA723DA332200B2                          | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 51       | https://github.com/i7495           | CE335B8803B8898E                          | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 52       | https://github.com/marx2019        | C8083472E22D5476                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| ~~53~~   | ~~https://github.com/wuyunjiao~~   | New Github Account~~553D2D5BAC15E8B8~~    | ~~150~~ | ~~0~~  | ~~50~~ | ~~20~~ | ~~30~~ | ~~10~~ | ~~10~~ | ~~10~~ | ~~10~~ | ~~10~~ | ~~0~~  |
| 54       | https://github.com/mayt613         | 3EDC046A95C6D3D3                          | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 55       | https://github.com/Steepouyang     | F09FF586F5000416                          | 350     | 0      | 50     | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 56       | https://github.com/ABEF            | BE46BDB610AAB0EA                          | 80      | 0      | 0      | 20     | 30     | 10     | 10     | 10     | 0      | 0      | 0      |
| 57       | https://github.com/cachitu         | 909A480D5643CCC5                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 58       | https://github.com/farss           | F54C3A22392847AEC1EE5AD601721119CAE76A9E  | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 59       | https://github.com/zhanglianghui   | 49D02A7526022E7C                          | 300     | 0      | 0      | 20     | 30     | 10     | 10     | 10     | 10     | 10     | 200    |
| 60       | https://github.com/eon0001         | D54C8032CF19C407                          | 0       | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      |
| 61       | https://github.com/samscau         | 70FA19B71FE14D20                          | 20      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 10     | 10     | 0      |
| 62       | https://github.com/b-harvest       | BFAAF68BD473D23958D452708957C5091FBF4192  | 200     | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 0      | 200    |

**Comment by weiwenlong555** [comment]
HLT 节点v0.14 Task 2 任务好像完成过了，但是忘记怎么查询完成的结果了

**Comment by shiknian** [comment]
Congratulations!^_^

**Comment by zhangyelong** [comment]
> HLT 节点v0.14 Task 2 任务好像完成过了，但是忘记怎么查询完成的结果了

好像没有哦，v0.14 的任务统计在这里，给大家时间确认过的：https://github.com/irisnet/testnets/issues/293

**Comment by weiwenlong555** [comment]
> > HLT 节点v0.14 Task 2 任务好像完成过了，但是忘记怎么查询完成的结果了
> 
> 好像没有哦，v0.14 的任务统计在这里，给大家时间确认过的：#293

嗯嗯，谢谢啦
