### ISSUE TITLE
如何通过完成测试网的任务获得相应奖励

### ISSUE THREAD

**Issue by kidinamoto01** [irisnet/testnets#46]
# 如何通过完成测试网的任务获得相应奖励

## IRISnet的测试激励计划目的是什么？ 

- 让更多技术人员熟悉IRISnet网络架构
- 让更多技术人员熟悉基于权益证明PoS的区块链的工作原理：验证人、委托人相关概念
- 让更多技术人员熟悉运行和维护一个PoS网络中验证人节点的要点
- 寻找使区块链网络更加安全可靠的解决方案

### 参与方式

* 通过[keybase.io](https://www.keybase.io)获得自己专属的pgp ID 。

* 填写此[表格](http://cn.mikecrm.com/H9aoXak)来完成注册。

Note:  只有前20名才能获得奖励！

### 任务列表
| 编号 | 名称                                  | 实现细节                                                   | 评判标准                                                     | 奖励     |
| ---- | ------------------------------------- | ---------------------------------------------------------- | ------------------------------------------------------------ | -------- |
| 1    | Setup a Full node                     | set up a full node and use `name-pgpid` as `monkier`       | Submit your IP and thr team could check the configutration of your node | 100 iris |
| 2    | Complete one token transaction        | Create an account, and send this new account some **iris** | Run this send transaction with your `name-pgpid` as memo. Submit your transaction hash and the team could verify the details of transaction | 20 iris  |
| 3    | Delegate some **iris** to a validator | Get some **iris** from faucet and delegate to a validator  | Run this send transaction with your `name-pgpid` as memo. Submit your transaction hash and the team could verify the details of transaction | 100 iris |
| 4    | Unbond some **iris** from a validator | Complete an unbond transaction                             | Run `unbond begin` and `unbond complete` transaction with your `name-pgpid` as memo. Submit your transaction hash and the team could verify the details of transaction | 100 iris |
举例:

1. Full node info

2. **Details of a transaction:**

   Command:

   ```
   iriscli advanced tendermint tx F6627E89466151C95C4381D5AB4EB5AB5E81D78C
   ```
   The output:
   ```
   {
     "hash": "F6627E89466151C95C4381D5AB4EB5AB5E81D78C",
     "height": "15499",
     "tx": {
       "type": "auth/StdTx",
       "value": {
         "msg": [
           {
             "type": "cosmos-sdk/Send",
             "value": {
               "inputs": [
                 {
                   "address": "faa1893x4l2rdshytfzvfpduecpswz7qtpstpr9x4h",
                   "coins": [
                     {
                       "denom": "iris",
                       "amount": "10"
                     }
                   ]
                 }
               ],
               "outputs": [
                 {
                   "address": "faa1uj5gfwrklrdzgqjwh0mnayclamkcy3jumg8g06",
                   "coins": [
                     {
                       "denom": "iris",
                       "amount": "10"
                     }
                   ]
                 }
               ]
             }
           }
         ],
         "fee": {
           "amount": [
             {
               "denom": "",
               "amount": "0"
             }
           ],
           "gas": "200000"
         },
         "signatures": [
           {
             "pub_key": {
               "type": "tendermint/PubKeySecp256k1",
               "value": "A3eTe0+O8flcd9rEDgC/DVmPCWayZBuJxf6AdVnG+IGY"
             },
             "signature": {
               "type": "tendermint/SignatureSecp256k1",
               "value": "MEUCIQCsNb2ylR+kefwqrlAz0WA1azbcq1B7LH0ZD/bop0DQuQIgTQ2LwWPP5sr9ObjU5dUiSlg8TZmQztORKyCPXEiRqQA="
             },
             "account_number": "15",
             "sequence": "56"
           }
         ],
         "memo": "suyu-5AF45A077B12D406"
       }
     },
     "result": {
       "log": "Msg 0: ",
       "gas_used": "3507",
       "tags": [
         {
           "key": "c2VuZGVy",
           "value": "ZmFhMTg5M3g0bDJyZHNoeXRmenZmcGR1ZWNwc3d6N3F0cHN0cHI5eDRo"
         },
         {
           "key": "cmVjaXBpZW50",
           "value": "ZmFhMXVqNWdmd3JrbHJkemdxandoMG1uYXljbGFta2N5M2p1bWc4ZzA2"
         }
       ],
       "fee": {}
     }
   }
   ```

3. Delegate some tokens

   Command:

   ```
   iriscli advanced tendermint tx FF3E52C1CB69C8050E93FAF7165EDC52502710F9
   ```

   The output:

   ```
   iriscli advanced tendermint tx FF3E52C1CB69C8050E93FAF7165EDC52502710F9
   {
     "hash": "FF3E52C1CB69C8050E93FAF7165EDC52502710F9",
     "height": "15621",
     "tx": {
       "type": "auth/StdTx",
       "value": {
         "msg": [
           {
             "type": "cosmos-sdk/MsgDelegate",
             "value": {
               "delegator_addr": "faa1uj5gfwrklrdzgqjwh0mnayclamkcy3jumg8g06",
               "validator_addr": "faa1uj5gfwrklrdzgqjwh0mnayclamkcy3jumg8g06",
               "delegation": {
                 "denom": "iris",
                 "amount": "10"
               }
             }
           }
         ],
         "fee": {
           "amount": [
             {
               "denom": "",
               "amount": "0"
             }
           ],
           "gas": "200000"
         },
         "signatures": [
           {
             "pub_key": {
               "type": "tendermint/PubKeySecp256k1",
               "value": "At4WnZ3aLJsvCUb59rhPRJkYWTFNTJrPjLn4jUT7VN1F"
             },
             "signature": {
               "type": "tendermint/SignatureSecp256k1",
               "value": "MEQCIFP1/kZxjD9KYM0B6b9pIUarVO0blPtsC2vj5lWKkYg6AiA0blXXJ5M/gD3EUMixzTM0sDbn65+KmgBijsL5hX3pQw=="
             },
             "account_number": "10",
             "sequence": "2"
           }
         ],
         "memo": "suyu-5AF45A077B12D406"
       }
     },
     "result": {
       "log": "Msg 0: ",
       "gas_used": "14796",
       "tags": [
         {
           "key": "YWN0aW9u",
           "value": "ZGVsZWdhdGU="
         },
         {
           "key": "ZGVsZWdhdG9y",
           "value": "ZmFhMXVqNWdmd3JrbHJkemdxandoMG1uYXljbGFta2N5M2p1bWc4ZzA2"
         },
         {
           "key": "ZGVzdGluYXRpb24tdmFsaWRhdG9y",
           "value": "ZmFhMXVqNWdmd3JrbHJkemdxandoMG1uYXljbGFta2N5M2p1bWc4ZzA2"
         }
       ],
       "fee": {}
     }
   }
   ```

4. Unbond your delegation

   ​

```
{
  "hash": "B9A1A64BBCAFE31D13D0D9DE00BB4DC883BC4F42",
  "height": "15676",
  "tx": {
    "type": "auth/StdTx",
    "value": {
      "msg": [
        {
          "type": "cosmos-sdk/BeginUnbonding",
          "value": {
            "delegator_addr": "faa1uj5gfwrklrdzgqjwh0mnayclamkcy3jumg8g06",
            "validator_addr": "faa1uj5gfwrklrdzgqjwh0mnayclamkcy3jumg8g06",
            "shares_amount": "10"
          }
        }
      ],
      "fee": {
        "amount": [
          {
            "denom": "",
            "amount": "0"
          }
        ],
        "gas": "200000"
      },
      "signatures": [
        {
          "pub_key": {
            "type": "tendermint/PubKeySecp256k1",
            "value": "At4WnZ3aLJsvCUb59rhPRJkYWTFNTJrPjLn4jUT7VN1F"
          },
          "signature": {
            "type": "tendermint/SignatureSecp256k1",
            "value": "MEQCICf5W4CrVDSEW1D7cRIEyM0Eaye5wScN3UQwMTs2Yeo+AiBG23eLvIDeB2rOyhm3FIH6HhBmM1pFfecDnQbXXr828g=="
          },
          "account_number": "10",
          "sequence": "3"
        }
      ],
      "memo": "suyu-5AF45A077B12D406"
    }
  },
  "result": {
    "log": "Msg 0: ",
    "gas_used": "16695",
    "tags": [
      {
        "key": "YWN0aW9u",
        "value": "YmVnaW4tdW5ib25kaW5n"
      },
      {
        "key": "ZGVsZWdhdG9y",
        "value": "ZmFhMXVqNWdmd3JrbHJkemdxandoMG1uYXljbGFta2N5M2p1bWc4ZzA2"
      },
      {
        "key": "c291cmNlLXZhbGlkYXRvcg==",
        "value": "ZmFhMXVqNWdmd3JrbHJkemdxandoMG1uYXljbGFta2N5M2p1bWc4ZzA2"
      }
    ],
    "fee": {}
  }
}
```

## 如何证明完成

通过提交相关交易的Hash。

```
GitHub ID: XXXX
pgp ID: XXX
Task 1:  link to check the config of your ：ip:26657/status
Task 2: Hash
Task 3: Hash
Task 4: Hash（both begin and complete）
```

**Comment by yunkunrao** [comment]
GitHub ID : yunkunrao
pgp ID : 90E4A60F4E84E674
Task 1 : 47.90.98.38:26657/status
Task 2 : 5604B13ADF2A8D36DBEA598C89D79E76A8A40E61
Task 3 : 29B53D266E324D0EA6AD29868D6FBB69EF360D6E
Task 4 : 2410FB67FC8FC512439EDC0EAC77F2E3E7063B78 (ubond complete operation which takes some time will be done later.)

**Comment by liangping** [comment]
GitHub ID: liangping
pgp ID: liangping
Task 1:  link to check the config of your ：47.91.237.180:26657/status
Task 2: 
send： 53B042DE87E00C61BB353C3148A5E136C03B7B74
Task 3: 
delegate: 122F0C236E0AC2BA026FFFC2C578788C2D128317
Task 4: Hash
unbond begin:3E49AD6BE95CA96DF92FBA613EBC46438B1A81A1

**Comment by locta66** [comment]
GitHub ID: locta66
pgp ID: yuereer 4E9C3E06AA9686BA
Task 1: link to check the config of your ：http://115.159.195.214:26657/status
Task 2:
send： 11539688BAAEAE11C6F128E0731B79495ABD2F7D
Task 3:
delegate: 6D879BEB529484103DCA10FAF0F32F6C2AE3F264 
Task 4: Hash
unbond begin:D2D0B37B49DC19ACF4DACB0F34F1480E02AB08B7
unbond complete: A8EDCB77B148A7A7F673F84E6A53C351F53552DC

**Comment by Night-mk** [comment]
GitHub ID: Night-mk
pgp ID: 3D1BBB690AB8AF6B
Task 1: 
	13.230.30.99:26657/status
Task 2: 
	send:9C320EB272CF85474B24AE9F440C32999157438B
Task 3: 
	delegate:68D094B8D444291D0BDD2F5F603CDB1C9F58D766
Task 4: 
	unbound begin: 59F8CD6A970EC355DA9C2318812A4B35232EAC06

**Comment by programokey** [comment]
请将所有任务完成结果提交到同一个comment里，如果提交多个comment将以最后一个comment为准。Task1的前20名完成者为前20个提交comment的参与者，其他Task的前20名以comment中提交的交易哈希的时间戳确定。

**Comment by mahuaibo** [comment]
GitHub ID: mahuaibo
pgp ID: 9B75D5E7320419BB
Task 1:  link to check the config of your ：http://47.254.32.219:26657/status
Task 2: Hash EC9D224BA830CD0464199F1C9BCAF974EB08E584
Task 3: Hash D7BEC27121FCA3206738E081A3305EC55BC0934C
Task 4: Hash 
unbond begin: 4B67805F17D1CA9EBFDC6E0F320FE44C512EC427
unbond complete: 6170669C85301C396E75F04DC96A777E44FB70F1

**Comment by programokey** [comment]
再次说明一下，必须要在执行交易时添加 --memo="<注册名-pgpid>"作为备注。未添加备注的交易不作为完成任务的依据。

**Comment by chenatu** [comment]
GitHub ID: chenatu
pgp ID: 7F5CB42406F1B4A6
Task1: http://66.42.107.152:26657/status
Task2: 0AA8BFAC0F2BD25A4A02BEC2DC2D690F113F2B29
Task3: 93EDB399D516221844E75147185ED0F12C60C2FC
Task4:
unbound begin: 213E57B74FE95AC01FB58D06A2A8C4BE4B3C0DE7
unbound complete: TBD

**Comment by walter211** [comment]
好像好多人都不对

**Comment by fjchen7** [comment]
GitHub ID: fjchen7
pgp ID : 0C355F4595098983
Task 1 : 47.74.183.232:26657/status
Task 2 : F41DD65F0F353EA8691AA1DABD80217DD7CAC238
Task 3 : 2B41048C3AB76922A6228DC47B151C3686E74423
Task 4 :
unbond begin : 1E0BADA6389B45D3CB1D88BFD2F7B4AB16BA122D
unbond complete: C1872E892F3840AF30BF5E211E86FC951FC73F65

**Comment by programokey** [comment]
pgp ID : D3286974B6068F4E
Task1 http://39.104.16.237:26657/status
Task2 send	Committed at block 177702. Hash: 6A143BFCCD91820F1A0BB76D975B54D82507937D 
Task3 delegate	Committed at block 177727. Hash: 4726F927C820BC13B0CD827C3A1F5DC2C7572E83
Task4  unbond begin	Committed at block 177746. Hash: 7551F32E13BC5BAF79FCAD42081B17F0FDFD40BF 
unbond complete	Committed at block 179694. Hash: 5FF637D401A0CAE68EBCB38AE298308E4F120A24

**Comment by walter211** [comment]
GitHub ID: walter211
pgp ID: 543EEBF810A2D68A
Task1:  http://122.112.218.45:26657/status
Task2: 61E323DE0514E405425EBB680A710EA13C111551
Task3: 0CE2E9BCF088F217BBC6B12A7F572BC9F7C964A9
Task4:
unbound begin: 8535B0BA6005BFF5A5858E3BDB5C8B883202D7A2
unbound complete: 7A75BF8CE0069DE25A617FBED653F1120F80C81F

**Comment by luckybean** [comment]
GitHub ID: luckybean
pgp ID: 8E15046A255C20CC
Task1: http://13.58.19.0:26657/status
Task2: 44E85B61AC33A6F392BAEF063FE0BBFF144A2607
Task3: 1D32199898A5B39EFA503EBC9D8F87768EB5C708
Task4:
unbound begin: 7066512C9354865E8265222CD97AEB3DC09E57FC
unbound complete: 743F94E49AB8FB0D26A612E1CDE27744EA65D5FE

**Comment by phantomk** [comment]
GitHub ID: phantomk
pgp ID: BF4B1C55A2B62090
Task1: http://47.105.73.253:26657/status
Task2: 40766C7D91C0BE134D79CE9CA28EFB139B7388FB
Task3: DFEA3AD93D31E12B7114AECD5BF3630C7FBEAD6C
Task4:
unbound begin: 33E6B5D1FF0D01277ADD98328378EC7D12C67D31
unbound complete: C50677E6E50D56B34F36610F0047D65E08130804

**Comment by shufanwu** [comment]
GitHub ID: shufanwu
pgp ID: A2CDF11C9C9B3DDB
Task1: http://118.25.130.132:26657/status
Task2: F9BC7A40D23C24D5EB54AA40DF99039A87778F2F
Task3: 994FCCF5D79BF99F1D97EE30DDBF232F0F988179
Task4:
unbound begin: 813ECBFDD1B7ABBE4FD99D18345644EB95F18C28
unbound complete: A5BCA921554018C835AA8B6C1C60BCCA437A1FC3

**Comment by KunPengRen** [comment]
GitHub  ID:KunPengRen
pgp ID:65909B956DF0F488
Task 1: link to check the config of your ：http://123.207.75.151:26657/status
Task 2:82D93617322D62EE38E5FD035C7F9DF55E251F06
Task 3:68EAF8FEF011C5EC8BC6B2AD0E74DF728A143562
Task 4: 
unbond begin:5163DE14CD2A8A2B01AC339F6320C80537AADBE6
unbond complete:7D7B5C82CF7AD739580DA8E1273F02D5AB196247

**Comment by adrianbrink** [comment]
@kidinamoto01 Should I sign up here as well?

**Comment by kwunyeung** [comment]
GitHub ID: kwunyeung
pgp ID: 3B84437810397048
Task 1: http://35.194.161.232:26657/status
Task 2: 23034E8C7A2556471367B98E49FE20C8098119A2
Task 3: DAF6F91FD71F56D21B2EDB1E90FA098472453BA7
Task 4:
unbond begin: 2114D9BCBFACADF2A3A096EEE3CCC385AB6D758C
unbond complete: 22BE1D5F55DEE7667F3CF82BFF1059EBAC55F06A

**Comment by terencesflam** [comment]
GitHub ID: terencesflam
pgp ID: D62DB1D7C532946D
Task1: http://35.237.174.91:26657/status
Task2: 51F389B571B9F80F4AEF42DFA0EB5390C6EF74EB 
Task3: DB7CC2B32BDEB45DC2CFDBFF0D9273A2BCFA2FDD
Task 4: 
unbond begin: 98D849774E6670327DE992A588906150130779F1
unbond complete: 980D6D3F637AA61E86C52321085204032AACEFAE
