### ISSUE TITLE
submission of gentx-node-ID.json for participation of genesis process

### ISSUE THREAD

**Issue by fanglei80** [irisnet/testnets#48]
{
"node_id": "efe5c369a1bf7c89fe6fba1fb96719a0a8aa3f94",
    "ip": "180.97.204.33",
    "validator": {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "r5Q8yWT2B0EgY0qEGCWTn8eR6lS2Up92PZYdDumBHi4="
      },
      "power": "100",
      "name": ""
    },
    "app_gen_tx": {
      "name": "fanglei",
      "address": "faa1ek05twny5rja0ay9ejuets5v26glzstrmkcd0r",
      "pub_key": "fap1zcjduepq472rejty7cr5zgrrf2zpsfvnnlrer6j5keff7a3ajcwsa6vprchq22qlav"
    }

am i doing correct thing? is the data that the team requesting for?

**Comment by zhangyelong** [comment]
Thanks but wrong place to upload your gentx, fuxi-3000 is coming, you may reupload your gentx to fuxi/fuxi-3000/config/gen-tx/
