### ISSUE TITLE
i cant setup a node for testnet, readme link is broken.

### ISSUE THREAD

**Issue by iammelea** [irisnet/testnets#62]
**
Getting Started

To get started with the latest testnet, please follow this guide.**

https://github.com/kidinamoto01/testnets-1/tree/master/testnets/docs

**Comment by kidinamoto01** [comment]
@iammelea sorry for the trouble, it should be fixed now

**Comment by iammelea** [comment]
you no need sorry. i am the last but the more impatient. ;)
