### ISSUE TITLE
Token Claimer 获得测试网IRIS

### ISSUE THREAD

**Issue by kidinamoto01** [irisnet/testnets#69]
Please reply this issue with your own account.

请将生成的用于测试网的地址回复在下面。

**Comment by mattharrop** [comment]
Figment, keybase ID 60C1D5AF5EE3F73 is up on game-of-genesis.  We'd like to claim our test tokens to faa10wl8d5wjhur4trsjdj04n0w542r9hmyc2l7af0 please!

**Comment by iammelea** [comment]
melea-trust keybase ID 4BE49EABAA41B8BF

need Tokens for start the next step of the game.

faa12ex66eaehdsg94k6qljfh8zj8lnphaycscu6pu

last sync 
```
iriscli status
{"node_info":{"id":"a2883613e6d665xxxxxxxxxx5789b0a97999","listen_addr":","network":"game-of-genesis","version":"0.22.6","channels":"40202122233038","moniker":"melea-trust-4BE49EABAA41B8BF-,"other":,"sync_info":{"latest_block_hash":"7C4BDBDEEC7D9F736BAB81CC1CA211A6A6FF533E","latest_app_hash":"A6F50789CBC11B47B1981D52AD873350FCA0561A","latest_block_height":"8625","latest_block_time":"2018-09-03T20:34:36.662127859Z","catching_up":false},
```

**Comment by paveltaranenko** [comment]
> iriscli account  faa1ezhrtpgdau06kfgnf9n8pm7kzuufmpqqs7x443
> ERROR: No account with address faa1ezhrtpgdau06kfgnf9n8pm7kzuufmpqqs7x443 was found in the state.
> Are you sure there has been a transaction involving it?

**Comment by beichenh** [comment]
Still haven't received test IRIS after sending the request one day ago...
